-- Db2 13 for z/OS - Client/Order sample schema
-- Schema: CLAPP  Database: CLDB01  Uses default stogroup SYSDEFLT
CREATE SCHEMA CLAPP;

CREATE DATABASE CLDB01 STOGROUP SYSDEFLT CCSID EBCDIC;

CREATE TABLESPACE TSCL01 IN CLDB01 USING STOGROUP SYSDEFLT PRIQTY 100 SECQTY 100 BUFFERPOOL BP0 CLOSE NO LOCKSIZE ROW;
CREATE TABLESPACE TSOR01 IN CLDB01 USING STOGROUP SYSDEFLT PRIQTY 100 SECQTY 100 BUFFERPOOL BP0 CLOSE NO LOCKSIZE ROW;

CREATE TABLE CLAPP.CLIENTS (
    CLIENT_ID   CHAR(10)     NOT NULL,
    NAME        VARCHAR(35)  NOT NULL,
    EMAIL       VARCHAR(60),
    PHONE       VARCHAR(20),
    STATUS      VARCHAR(10)  NOT NULL WITH DEFAULT 'ACTIVE',
    CREATED_TS  TIMESTAMP    NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (CLIENT_ID)
) IN CLDB01.TSCL01;

CREATE TABLE CLAPP.ORDERS (
    ORDER_ID    CHAR(12)     NOT NULL,
    CLIENT_ID   CHAR(10)     NOT NULL,
    ORDER_DATE  DATE         NOT NULL,
    STATUS      VARCHAR(12)  NOT NULL WITH DEFAULT 'NEW',
    TOTAL_AMT   DEC(11,2)    NOT NULL WITH DEFAULT 0,
    CREATED_TS  TIMESTAMP    NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_ORD_CLIENT FOREIGN KEY (CLIENT_ID)
        REFERENCES CLAPP.CLIENTS (CLIENT_ID)
        ON DELETE RESTRICT
) IN CLDB01.TSOR01;

CREATE INDEX CLAPP.IX_ORD_CLIENT ON CLAPP.ORDERS(CLIENT_ID);

-- Optional: basic privileges (adjust AUTHID)
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE CLAPP.CLIENTS TO PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE CLAPP.ORDERS  TO PUBLIC;
