       IDENTIFICATION DIVISION.
       PROGRAM-ID.  ZFT2PAIN.
       AUTHOR.      Generated by M365 Copilot.
       DATE-WRITTEN. 2026-03-12.
      * -----------------------------------------------------------------
      * Purpose:
      *   - Read FB(80) sequential dataset of funds transfer requests.
      *   - Build a SEPA pain.001.001.03 XML document using XML GENERATE.
      *   - Write the UTF-8 encoded XML into a VB dataset (multiple
      *     variable-length records if needed).
      *
      * Input record layout (LRECL=80, RECFM=FB):
      *   1-16   END-TO-END_ID        (X(16))
      *  17-29   AMOUNT_IN_CENTS      (9(13))  -- implied 2 decimals
      *  30-51   CREDITOR_IBAN_DE     (X(22))  -- German IBAN (22 chars)
      *  52-80   CREDITOR_NAME        (X(29))
      *
      * Output: UTF-8 pain.001.001.03 in a VB dataset.
      * -----------------------------------------------------------------
       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT INFILE  ASSIGN TO SYS010.
           SELECT OUTFILE ASSIGN TO SYS020.

       DATA DIVISION.
       FILE SECTION.
       FD  INFILE
           RECORDING MODE IS F
           RECORD CONTAINS 80 CHARACTERS
           BLOCK CONTAINS 0.
       01  IN-REC.
           05 IR-END2END             PIC X(16).
           05 IR-AMOUNT-CENTS        PIC 9(13).
           05 IR-IBAN                PIC X(22).
           05 IR-NAME                PIC X(29).

       FD  OUTFILE
           RECORDING MODE V
           RECORD IS VARYING IN SIZE FROM 1 TO 32756
           DEPENDING ON OUT-LEN
           BLOCK CONTAINS 0.
       01  OUT-REC                   PIC X(32756).

       WORKING-STORAGE SECTION.
       77  OUT-LEN                   PIC 9(5) COMP VALUE 0.
       77  EOF                       PIC X VALUE 'N'.
       77  WS-COUNT                  PIC 9(9) VALUE 0.
       77  WS-CNTRL-SUM-CENTS        PIC 9(18) VALUE 0.

      * Debtor / header defaults
      * (adjust via source or add simple PARM parsing)
       01  WS-PARAMS.
           05 WS-INITG-NAME      PIC X(70) VALUE 'Demo Debtor GmbH'.
           05 WS-DEBTOR-NAME     PIC X(70) VALUE 'Demo Debtor GmbH'.
           05 WS-DEBTOR-IBAN     PIC X(34)
                                 VALUE 'DE44500105175407324931'.
           05 WS-DEBTOR-BIC      PIC X(11) VALUE 'COBADEFFXXX'.
           05 WS-CURRENCY        PIC X(3)  VALUE 'EUR'.
           05 WS-MSG-ID          PIC X(35) VALUE 'MSG-0001'.
           05 WS-PMTINF-ID       PIC X(35) VALUE 'PMTINF-0001'.
           05 WS-REQ-EXEC-DATE   PIC X(10) VALUE '2026-03-13'.

      * Table to store transactions read from the input
       77  MAX-TX                    PIC 9(4) VALUE 2000.
       01  TX-TABLE.
           05 TX OCCURS 0 TO 2000 DEPENDING ON WS-COUNT.
              10 TX-END2END          PIC X(35).
              10 TX-AMT-DEC          PIC X(20).
              10 TX-AMT-CCY          PIC X(3)  VALUE 'EUR'.
              10 TX-CDTR-NAME        PIC X(70).
              10 TX-CDTR-IBAN        PIC X(34).
              10 TX-REMIT            PIC X(140).

      * XML output buffer
       01  XML-OUT                   PIC X(250000).
       77  XML-LEN                   PIC 9(9) COMP VALUE 0.

      * pain.001 COBOL structure to feed XML GENERATE
       01  DOCUMENT.
           05 CstmrCdtTrfInitn.
              10 GrpHdr.
                 15 MsgId             PIC X(35).
                 15 CreDtTm           PIC X(19).
                 15 NbOfTxs           PIC 9(9).
                 15 CtrlSum           PIC X(30).
                 15 InitgPty.
                    20 Nm             PIC X(70).
              10 PmtInf.
                 15 PmtInfId          PIC X(35).
                 15 PmtMtd            PIC X(3).
                 15 BtchBookg         PIC X(5).
                 15 NbOfTxs2          PIC 9(9).
                 15 CtrlSum2          PIC X(30).
                 15 PmtTpInf.
                    20 SvcLvl.
                       25 SvcCode     PIC X(4).
                 15 ReqdExctnDt       PIC X(10).
                 15 Dbtr.
                    20 Nm             PIC X(70).
                 15 DbtrAcct.
                    20 DbtrAcctId.
                       25 IBAN        PIC X(34).
                    20 Ccy            PIC X(3).
                 15 DbtrAgt.
                    20 FinInstnId.
                       25 BIC         PIC X(11).
                 15 ChrgBr            PIC X(4).
                 15 CdtTrfTxInf OCCURS 0 TO 2000
                                DEPENDING ON WS-COUNT.
                    20 PmtId.
                       25 InstrId     PIC X(35).
                       25 EndToEndId  PIC X(35).
                    20 Amt.
                       25 InstdAmt    PIC X(20).
                       25 InstdAmtCcy PIC X(3).
                    20 Cdtr.
                       25 Nm          PIC X(70).
                    20 CdtrAcct.
                       25 CdtrAcctId.
                          30 IBAN     PIC X(34).
                    20 RmtInf.
                       25 Ustrd       PIC X(140).

       01  WS-DATE-TIME.
           05 WS-DATE                PIC 9(8).
           05 WS-TIME                PIC 9(6).

       01  WS-AUX.
           05 SUM-INT      PIC 9(18) VALUE 0.
           05 SUM-FRAC     PIC 9(2)  VALUE 0.
           05 AMT-INT      PIC 9(15) VALUE 0.
           05 AMT-FRAC     PIC 9(2)  VALUE 0.
           05 PTR          PIC S9(4) COMP VALUE 1.
           05 REM          PIC S9(4) COMP VALUE 0.

       PROCEDURE DIVISION.
       MAIN-LOGIC SECTION.
           OPEN INPUT INFILE
                OUTPUT OUTFILE.

           PERFORM READ-LOOP UNTIL EOF = 'Y'

           PERFORM BUILD-PAIN-STRUCTURE
           PERFORM GENERATE-AND-WRITE-XML

           CLOSE INFILE OUTFILE
           GOBACK
           .
           EXIT.

       READ-LOOP SECTION.
           READ INFILE
               AT END MOVE 'Y' TO EOF
               NOT AT END
                 ADD 1 TO WS-COUNT
                 PERFORM LOAD-TX-FROM-REC
           END-READ
           .
           EXIT.

       LOAD-TX-FROM-REC SECTION.
      * Amount as cents (13 digits) -> decimal string with '.'
      * Convert to unsigned integer, then produce 2 decimal places
      * Move EndToEndId (left-trim spaces)
           MOVE FUNCTION TRIM(IR-END2END) TO TX-END2END(WS-COUNT)

      * Build decimal amount: integer part and fractional part
           IF IR-AMOUNT-CENTS IS NUMERIC
           THEN
              MOVE IR-AMOUNT-CENTS TO WS-CNTRL-SUM-CENTS
              ADD  IR-AMOUNT-CENTS TO WS-CNTRL-SUM-CENTS
           END-IF

           PERFORM VARYING OUT-LEN FROM 1 BY 1 UNTIL OUT-LEN > 1
              EXIT PERFORM
           END-PERFORM

      * Compute amount string XX...X.XX
      *    CALL 'CEEDIV' USING IR-AMOUNT-CENTS 100 OMITTED OMITTED

      * Fallback simple formatting (no LE intrinsic available here),
      * so do manual split.
           MOVE IR-AMOUNT-CENTS TO AMT-INT
           DIVIDE AMT-INT BY 100 GIVING AMT-INT REMAINDER AMT-FRAC
           STRING AMT-INT  DELIMITED BY SIZE
                  '.'      DELIMITED BY SIZE
                  AMT-FRAC DELIMITED BY SIZE
                  INTO TX-AMT-DEC(WS-COUNT)
           END-STRING
           IF AMT-FRAC < 10
           THEN
              STRING FUNCTION TRIM(TX-AMT-DEC(WS-COUNT))
                     '0' DELIMITED BY SIZE
                     INTO TX-AMT-DEC(WS-COUNT)
              END-STRING
           END-IF

           MOVE 'EUR'                   TO TX-AMT-CCY(WS-COUNT)
           MOVE FUNCTION TRIM(IR-NAME)  TO TX-CDTR-NAME(WS-COUNT)
           MOVE FUNCTION TRIM(IR-IBAN)  TO TX-CDTR-IBAN(WS-COUNT)
           MOVE 'Remittance'            TO TX-REMIT(WS-COUNT)
           .
           EXIT.

       BUILD-PAIN-STRUCTURE SECTION.
      * Populate the DOCUMENT structure from WS-PARAMS
           ACCEPT WS-DATE FROM DATE YYYYMMDD
           ACCEPT WS-TIME FROM TIME

           MOVE WS-MSG-ID     TO MsgId
           STRING WS-DATE(1:4) '-' WS-DATE(5:2) '-' WS-DATE(7:2)
                   DELIMITED BY SIZE
                  'T'  DELIMITED BY SIZE
                  WS-TIME(1:2) ':' WS-TIME(3:2) ':' WS-TIME(5:2)
                  DELIMITED BY SIZE
                  INTO CreDtTm
           END-STRING
           MOVE WS-COUNT      TO NbOfTxs NbOfTxs2

      *   Control sum in euros with decimal separator '.'
           MOVE WS-CNTRL-SUM-CENTS TO SUM-INT
           DIVIDE SUM-INT BY 100 GIVING SUM-INT REMAINDER SUM-FRAC
           STRING SUM-INT  DELIMITED BY SIZE
                  '.'      DELIMITED BY SIZE
                  SUM-FRAC DELIMITED BY SIZE
                  INTO CtrlSum
           END-STRING
           MOVE CtrlSum TO CtrlSum2

           MOVE WS-INITG-NAME        TO InitgPty Nm OF InitgPty
           MOVE WS-PMTINF-ID         TO PmtInfId
           MOVE 'TRF'                TO PmtMtd
           MOVE 'true'               TO BtchBookg
           MOVE 'SEPA'               TO SvcCode OF SvcLvl
           MOVE WS-REQ-EXEC-DATE     TO ReqdExctnDt
           MOVE WS-DEBTOR-NAME       TO Nm OF Dbtr
           MOVE WS-DEBTOR-IBAN       TO IBAN OF DbtrAcctId OF DbtrAcct
           MOVE WS-CURRENCY          TO Ccy OF DbtrAcct
           MOVE WS-DEBTOR-BIC        TO BIC OF FinInstnId OF DbtrAgt
           MOVE 'SLEV'               TO ChrgBr

           PERFORM VARYING OUT-LEN FROM 1 BY 1 UNTIL OUT-LEN > WS-COUNT
             MOVE TX-END2END(OUT-LEN)
               TO EndToEndId   OF PmtId    OF CdtTrfTxInf(OUT-LEN)
             MOVE TX-END2END(OUT-LEN)
               TO InstrId      OF PmtId    OF CdtTrfTxInf(OUT-LEN)
             MOVE TX-AMT-DEC(OUT-LEN)
               TO InstdAmt     OF Amt      OF CdtTrfTxInf(OUT-LEN)
             MOVE TX-AMT-CCY(OUT-LEN)
               TO InstdAmtCcy  OF Amt      OF CdtTrfTxInf(OUT-LEN)
             MOVE TX-CDTR-NAME(OUT-LEN)
               TO Nm           OF Cdtr     OF CdtTrfTxInf(OUT-LEN)
             MOVE TX-CDTR-IBAN(OUT-LEN)
               TO IBAN OF CdtrAcctId OF CdtrAcct
                                           OF CdtTrfTxInf(OUT-LEN)
             MOVE TX-REMIT(OUT-LEN)
               TO Ustrd        OF RmtInf   OF CdtTrfTxInf(OUT-LEN)
           END-PERFORM
           .
           EXIT.

       GENERATE-AND-WRITE-XML SECTION.
      * Use XML GENERATE to produce UTF-8 encoded XML directly
      * into XML-OUT buffer, then write in chunks to the VB output.
           XML GENERATE XML-OUT
               FROM DOCUMENT
               COUNT IN XML-LEN
               WITH ENCODING 1208
      * ENCODING 1208 = UTF-8 (Unicode Transformation Format - 8-bit)
               WITH XML-DECLARATION
               NAMESPACE IS
                    "urn:iso:std:iso:20022:tech:xsd:pain.001.001.03"
               NAME OF DOCUMENT                  IS "Document"
                       CSTMRCDTTRFINITN          IS "CstmrCdtTrfInitn"
                       GrpHdr                    IS "GrpHdr"
                       MsgId                     IS "MsgId"
                       CreDtTm                   IS "CreDtTm"
                       NbOfTxs                   IS "NbOfTxs"
                       CtrlSum                   IS "CtrlSum"
                       InitgPty                  IS "InitgPty"
                       Nm OF InitgPty            IS "Nm"
                       PmtInf                    IS "PmtInf"
                       PmtInfId                  IS "PmtInfId"
                       PmtMtd                    IS "PmtMtd"
                       BtchBookg                 IS "BtchBookg"
                       NbOfTxs2                  IS "NbOfTxs"
                       CtrlSum2                  IS "CtrlSum"
                       PmtTpInf                  IS "PmtTpInf"
                       SvcLvl                    IS "SvcLvl"
                       SvcCode OF SvcLvl         IS "Cd"
                       ReqdExctnDt               IS "ReqdExctnDt"
                       Dbtr                      IS "Dbtr"
                       Nm OF Dbtr                IS "Nm"
                       DbtrAcct                  IS "DbtrAcct"
                       DbtrAcctId OF DbtrAcct    IS "Id"
                       IBAN OF DbtrAcctId OF DbtrAcct
                                                 IS "IBAN"
                       Ccy OF DbtrAcct           IS "Ccy"
                       DbtrAgt                   IS "DbtrAgt"
                       FinInstnId                IS "FinInstnId"
                       BIC                       IS "BIC"
                       ChrgBr                    IS "ChrgBr"
                       CdtTrfTxInf               IS "CdtTrfTxInf"
                       PmtId                     IS "PmtId"
                       InstrId                   IS "InstrId"
                       EndToEndId                IS "EndToEndId"
                       Amt                       IS "Amt"
                       InstdAmt                  IS "InstdAmt"
                       InstdAmtCcy               IS "Ccy"
                       Cdtr                      IS "Cdtr"
                       Nm OF Cdtr                IS "Nm"
                       CdtrAcct                  IS "CdtrAcct"
                       CdtrAcctId OF CdtrAcct    IS "Id"
                       IBAN OF CdtrAcctId OF CdtrAcct
                                                 IS "IBAN"
                       RmtInf                    IS "RmtInf"
                       Ustrd                     IS "Ustrd"
               TYPE OF InstdAmtCcy               IS ATTRIBUTE
           END-XML

           IF XML-LEN > 0
           THEN
              PERFORM WRITE-CHUNKS
           END-IF
           .
           EXIT.

       WRITE-CHUNKS SECTION.
           MOVE XML-LEN TO REM
           PERFORM UNTIL REM <= 0
              COMPUTE OUT-LEN = FUNCTION MIN(REM, 4000)
              MOVE XML-OUT(PTR:OUT-LEN) TO OUT-REC
              WRITE OUT-REC
              ADD OUT-LEN TO PTR
              SUBTRACT OUT-LEN FROM REM
           END-PERFORM
           .
           EXIT.

       END PROGRAM ZFT2PAIN.